trigger:
- master

pool:
  name: 'Dengene-Agent'

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: build the project
    steps:
    - powershell: |
        Write-Output "Current directory before redirect: $(Get-Location)"  # PowerShell command to print the directory
        cd project  # Navigate to the 'project' directory
        Write-Output "Current directory after redirect: $(Get-Location)"  # PowerShell command to print the directory
        mvn clean install -DskipTests  # Run Maven build with tests skipped
      displayName: 'Build the Project without Running Tests'
