trigger:
- master

pool:
  name: 'Dengene-Agent'

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: build the project
    steps:
    - script: |
          cd project
          mvn clean install -DskipTests
      displayName: 'Build Without Running Tests'