trigger:
- master

pool:
  name: 'Dengene-Agent'

stages:
- stage: test
  displayName: Test Stage
  jobs:
  - job: TestUnitTest
    displayName: Unit Test
    steps:
      - powershell: |
          cd project 
          mvn test 
  - job: CodeCoverage
    displayName: Code Covarage Test
    condition: succeeded()
    steps:
      - powershell: |
          cd project 
          mvn test jacoco:report
- stage: build
  condition: succeeded()
  displayName: Build Stage
  jobs:
  - job: BuildJob

    displayName: build the project
    steps:
    - powershell: |
        cd project  # Navigate to the 'project' directory
        mvn clean install -DskipTests  # Run Maven build with tests skipped
      displayName: 'Build the Project without Running Tests'
    - powershell: |
        cd project 
        Copy-Item -Path .\unit_test_demo\target\*.jar -Destination "$(Pipeline.Workspace)\BuildOutput" -Recurse
      displayName: 'Save build Artifact'
    - powershell: |
        $artifactPath= $(Pipeline.Workspace)\BuildOutput\*.jar
        $artifactName = "BuildArtifact"
        Write-Output "Artifact Path: $artifactPath"
        Write-Output "Artifact Name: $artifactName"
        Copy-Item -Path $artifactPath -Destination "$(Build.ArtifactStagingDirectory)" -Recurse
      displayName: 'Publish Artifact'
