trigger:
- master

pool:
  name: 'Dengene-Agent'

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: build the project
    steps:
    - task: JavaToolInstaller@1
      inputs:
        versionSpec: '8'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: |
            cd project 
            mvn clean install -DskipTests
      displayName: 'Build without runing the test'
        # testResultsFiles: '**/surefire-reports/TEST-*.xml'
        # goals: 'package'
