trigger:
- master

pool:
  name: 'Dengene-Agent'

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: build the project
    steps:
    - script: |
        echo "$(pwd) before redirect"
        cd project
        echo "$(pwd) after "
        # mvn clean install -DskipTests